// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idzwvvvyumnwjbiefuhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkend2dnZ5dW1ud2piaWVmdWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NzEyNzUsImV4cCI6MjA2NDE0NzI3NX0.DBgyQc2BDlGnlxZ-STrG4p0FC3AM0OiLphMGjvPFrSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);